### ISSUE TITLE
switch to a safe and scalable DB interface

### ISSUE THREAD

**Issue by D1sk1n** [Disk1n/LibraBrowser#1]
currently using sqlite3 which won't hold in large scale + using it directly which is unsafe

**Comment by Disk1n** [comment]
@gdbaldw implemented SQLAlchemy usage in #24 
next we should add the configuration to choose DB backend and use alternatives to sqlite that are more scalable...

**Comment by Disk1n** [comment]
@gdbaldw added default pgsql + instructions in #25 
done! :)
