### ISSUE TITLE
Oh-oh! Libra testnet is down :-(

### ISSUE THREAD

**Issue by JoshLind** [Disk1n/LibraBrowser#44]
Hi,

When visiting your page (https://librabrowser.io/), it reports that the Libra testnet is down. However, when I view another explorer for the Libra testnet (e.g. https://libraview.org/ or https://libexplorer.com/), it appears the network is up?

Thanks!
Josh

**Comment by Disk1n** [comment]
Hi Josh,
Librabrowser.io is now operated and maintained by First Group (
https://www.firstdag.com/) and I am no longer involved...

Sincerely,
Gal Diskin

**Comment by JoshLind** [comment]
Hi Gal,

Great, thanks for letting me know!
