### ISSUE TITLE
add automatic handling for testnet reset

### ISSUE THREAD

**Issue by D1sk1n** [Disk1n/LibraBrowser#7]
might save old DB on the side and offer it to interested parties...

**Comment by Disk1n** [comment]
based on the first reset that happened 5 days ago it seems like the "latest block" will suddenly fall to a low number. Handling it properly should be backing up the DB and restarting the txs table

**Comment by gdbaldw** [comment]
This would have been useful today. Doable in SQLAlchemy, and will tackle this.

**Comment by Disk1n** [comment]
Done #29 #32
